import type { Metadata } from "next";
import { Questrial } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const questrial = Questrial({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${questrial.className} antialiased selection:bg-emerald-700/25`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
